# Generated by Django 4.0.10 on 2024-09-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='due_date',
            field=models.TextField(default='foobar'),
        ),
    ]
